config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("school_project.users.urls", namespace="users")),
    path('',include('school_project.basic.urls',namespace='basic'))    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

school_project/basic/urls.py
from django.urls import path

from school_project.basic.views import (
   HomePage,
   AboutPage,
   SubjectPage,
   EventPage,
   NewsPage,
   ContactPage,
   GalleryPage,
   GalleryDetail,
   CatgoryWiseGallery,
   NewsSingle,
   PrincipalMessageView,
   MoreAbout,
   DirectorMessageView
)

app_name = "basic"
urlpatterns = [
    path("", HomePage.as_view(), name="home_page"),
    path("about", AboutPage.as_view(), name="about_page"),
    path("subject", SubjectPage.as_view(), name="subject_page"),
    path("event", EventPage.as_view(), name="event_page"),
    path("news", NewsPage.as_view(), name="news_page"),
    path("contact", ContactPage.as_view(), name="contact_page"),
    path("gallery", GalleryPage.as_view(), name="gallery_page"),
    path("gallery/<int:id>", GalleryDetail.as_view(), name="gallery_detail"),
    path("gallery-category/<int:id>", CatgoryWiseGallery.as_view(), name="category_gallery"),
    path("news/<int:id>", NewsSingle.as_view(), name="news_single"),
    path("principal/", PrincipalMessageView.as_view(), name="principal_message"),
    path("director/", DirectorMessageView.as_view(), name="director_message"),
    path("more-about/", MoreAbout.as_view(), name="more-about"),
]

school_project/users/urls.py
from django.urls import path

from school_project.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

school_project/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from school_project.users.managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for school_project.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

school_project/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

school_project/basic/views.py
from django.shortcuts import render
from django.views import View
from school_project.basic.models import Information,SubjectWeTeach, Feedback,News,Gallery,Team,Events, Contact,GalleryCategory,BOD,AboutSchool, DirectorMessage, PrincipalMessage
from django.contrib import messages
from django.core.mail import send_mail
from config.settings.base import EMAIL_HOST_USER

class HomePage(View):
    def get(self,request, *args, **kwargs):
        info = Information.objects.get(id=1)
        subjects = SubjectWeTeach.objects.all()[:4]
        feedbacks = Feedback.objects.all()
        latest_news = News.objects.all()[:4]
        gallery = Gallery.objects.all()[:4]
        bod = BOD.objects.all()
        principal_message = PrincipalMessage.objects.all()[:2]
        director_message = DirectorMessage.objects.all()[:2]
        
        data = {
            'info':info,
            'subjects':subjects,
            'feedbacks':feedbacks,
            'latest_news':latest_news,
            'gallery':gallery,
            'bod':bod,
            'director_message':director_message,
            'principal_message':principal_message
            }
        return render(request, 'pages/home.html',data)
    
class AboutPage(View):
    def get(self,request, *args, **kwargs):
        info = Information.objects.get(id=1)
        subjects = SubjectWeTeach.objects.all()[:4]
        feedbacks = Feedback.objects.all()
        latest_news = News.objects.all()[:4]
        gallery = Gallery.objects.all()[:4]
        teams = Team.objects.all()
        bod = BOD.objects.all()
        about_school = AboutSchool.objects.all()[:2]
     
        
  
        data = {
            'info':info,
            'subjects':subjects,
            'feedbacks':feedbacks,
            'latest_news':latest_news,
            'gallery':gallery,
            'teams':teams,
            'bod':bod,
            'about_school':about_school
            }
        return render(request, 'pages/about.html',data)
    
    
class SubjectPage(View):
    def get(self,request, *args, **kwargs):
        info = Information.objects.get(id=1)
        subjects = SubjectWeTeach.objects.all()
        gallery = Gallery.objects.all()[:4]
        data = {
            'info':info,
            'subjects':subjects,
            'gallery':gallery,
            }
        return render(request, 'pages/subject.html',data)
    
class EventPage(View):
    def get(self,request, *args, **kwargs):
        info = Information.objects.get(id=1)
        events = Events.objects.all()
        gallery = Gallery.objects.all()[:4]
        data = {
            'info':info,
            'events':events,
            'gallery':gallery,
            }
        return render(request, 'pages/events.html',data)
    
class NewsPage(View):
    def get(self,request, *args, **kwargs):
        info = Information.objects.get(id=1)
        news = News.objects.all()
        gallery = Gallery.objects.all()[:4]
        recent_news = News.objects.all()[:3]
        data = {
            'info':info,
            'news':news,
            'gallery':gallery,
            'recent_news':recent_news
            }
        return render(request, 'pages/news.html',data)
    
class ContactPage(View):
    def get(self,request, *args, **kwargs):
        info = Information.objects.get(id=1)
        news = News.objects.all()
        gallery = Gallery.objects.all()[:4]
        recent_news = News.objects.all()[:3]
        data = {
            'info':info,
            'news':news,
            'gallery':gallery,
            'recent_news':recent_news
            }
        return render(request, 'pages/contact.html',data)
    
    def post(self, request, *args, **kwargs):
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        subject = request.POST.get('subject')
        send_mail(subject, message, EMAIL_HOST_USER, [email],fail_silently=False)
        contact = Contact.objects.create(first_name=first_name,last_name=last_name,email=email,phone_number=phone,comments=message,subject=subject)
        messages.success(request,"Thank you for reaching us, we will contact you soon!")
        
        return render(request, 'pages/contact.html')
    
class GalleryPage(View):
    def get(self,request, *args, **kwargs):
        info = Information.objects.get(id=1)
        galleries = Gallery.objects.all()
        gallery = Gallery.objects.all()[:4]
        gallery_categories = GalleryCategory.objects.all()
        data = {
            'info':info,
            'galleries':galleries,
            'gallery':gallery,
            'gallery_categories':gallery_categories
            }
        return render(request, 'pages/gallery.html',data)

class GalleryDetail(View):
    def get(self,request, id, *args, **kwargs):
        info = Information.objects.get(id=1)
        one_gallery = Gallery.objects.get(id=id)
        gallery = Gallery.objects.all()[:4]
        data = {
            'info':info,
            'one_gallery':one_gallery,
            'gallery':gallery,
            }
        return render(request, 'pages/gallery_detail.html',data)
class CatgoryWiseGallery(View):
    def get(self,request, id, *args, **kwargs):
        info = Information.objects.get(id=1)
        galleries = Gallery.objects.filter(category=id)
        print(galleries)
        gallery = Gallery.objects.all()[:4]
        gallery_categories = GalleryCategory.objects.all()
        data = {
            'info':info,
            'galleries':galleries,
            'gallery':gallery,
             'gallery_categories':gallery_categories
            }
        return render(request, 'pages/gallery.html',data)
    
class NewsSingle(View):
    def get(self,request, id, *args, **kwargs):
        info = Information.objects.get(id=1)
        news_single = News.objects.get(id=id)
        print(news_single)
        gallery = Gallery.objects.all()[:4]
        data = {
            'info':info,
            'single_news':news_single,
            'gallery':gallery,
            }
        return render(request, 'pages/single_news.html',data)
    

class PrincipalMessageView(View):
    def get(self, request):
        info = Information.objects.get(id=1)
        gallery = Gallery.objects.all()[:4]
        principal_message = PrincipalMessage.objects.all()
        
        data = {
            'info':info,
            'gallery':gallery,
            'principal_message':principal_message
            }
        return render(request, 'pages/principal_message.html',data)
    
class DirectorMessageView(View):
    def get(self, request):
        info = Information.objects.get(id=1)
        gallery = Gallery.objects.all()[:4]
        director_message = DirectorMessage.objects.all()
        
        data = {
            'info':info,
            'gallery':gallery,
            'director_message':director_message
            }
        return render(request, 'pages/director_message.html',data)
    

class MoreAbout(View):
    def get(self, request):
        info = Information.objects.get(id=1)
        gallery = Gallery.objects.all()[:4]
        about_school = AboutSchool.objects.all()
        data = {
            'info':info,
            'gallery':gallery,
            'about_school':about_school
            }
        return render(request, 'pages/about_more.html',data)

school_project/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

school_project/templates/pages/footer.html
<!-- footer -->
<footer class="footer-bg footer-p fix" style=" background-image: url(img/bg/footer-bg.png); background-repeat: no-repeat; background-position: center;">
    <div class="footer-top  pt-70 pb-40">
         <div class="container">
          <div class="row">
               <div class="col-xl-3 col-lg-3 col-sm-12">
                   <div class="footer-widget mb-30">
                    
                          <img src="{{info.school_logo.url}}" alt="img">
                       
                   </div>
               </div>
               <div class="col-xl-7 col-lg-7 col-sm-12">
                   <div class="footer-widget footer-link mt-20 text-center">
                           <ul>                                        
                               <li><a href="{% url 'basic:home_page' %}">Home</a></li>
                               <li><a href="{% url 'basic:about_page' %}"> About Us</a></li>
                               <li><a href="{% url 'basic:subject_page' %}"> Subject we teach </a></li>
                               <li><a href="{% url 'basic:event_page' %}"> Events</a></li>
                               <li><a href="{% url 'basic:news_page' %}">News </a></li>
                               <li><a href="{% url 'basic:contact_page' %}">Contact Us </a></li>
                           </ul>
                      
                       
                   </div>
               </div>
               <div class="col-xl-2 col-lg-2 col-sm-12">
                   <div class="footer-widget footer-social mt-15  text-right text-xl-right">
                           <a href="#"><i class="fab fa-facebook-f"></i></a>  
                           <a href="#"><i class="fab fa-instagram"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                          
                   </div>
               </div>
        </div>
        </div>
   </div>
   <div class="footer-center  pt-70 pb-40" >
       <div class="container">
           <div class="row justify-content-between">
               
               <div class="col-xl-3 col-lg-3 col-sm-6">
                   <div class="footer-widget mb-30">
                        <div class="f-widget-title">
                           <h2>About Us</h2>
                       </div>
                       <div class="footer-link">
                          {{info.about_school}}
                       </div>
                     
                   </div>
               </div>
                
                 <div class="col-xl-3 col-lg-3 col-sm-6">
                   <div class="footer-widget mb-30">
                         <div class="f-widget-title">
                           <h2>Contact Us</h2>
                       </div>
                       <div class="f-contact">
                           <ul>
                           <li>
                               <i class="icon fal fa-map-marker-check"></i>
                               <span>{{info.location}}</span>
                           </li>
                           <li>
                               <i class="icon fal fa-phone"></i>
                               <span>{{info.phone_number}}</span>
                           </li>
                          <li><i class="icon fal fa-envelope"></i>
                               <span>
                                   <a href="mailto:info@example.com">{{info.email}}</a>
                              <br>
                              </span>
                           </li>
                           
                            
                       </ul>
                           
                           </div>
                   </div>
               </div>
               <div class="col-xl-3 col-lg-3 col-sm-6">
                   <div class="footer-widget mb-30">
                       <div class="f-widget-title">
                           <h2>Our Services</h2>
                       </div>
                       <div class="footer-link">
                           <ul>                                        
                               <li><a href="{% url 'basic:home_page' %}">Home</a></li>
                               <li><a href="{% url 'basic:about_page' %}"> About Us</a></li>
                               <li><a href="{% url 'basic:subject_page' %}"> Subject we teach </a></li>
                               <li><a href="{% url 'basic:contact_page' %}"> Contact Us</a></li>
                               <li><a href="{% url 'basic:news_page' %}">News </a></li>
                           </ul>
                       </div>
                   </div>
               </div>
                 
             
                  <div class="col-xl-3 col-lg-3 col-sm-6">
                   <div class="footer-widget mb-30">
                       <div class="f-widget-title">
                           <h2>Our Gallery</h2>
                       </div>
                       <div class="f-insta">
                           <ul>
                               {% for image in gallery %}
                               <li><a href="#" class=" popup-image"><img src="{{image.image.url}}" alt="img"></a></li>
                               {% endfor %}
                           </ul>
                       </div>
                   </div>
               </div>  
              
           </div>
       </div>
   </div>
   <div class="copyright-wrap">
       <div class="container">
           <div class="row align-items-center">
               <div class="col-lg-6">                         
                      Copyright  &copy; 2023 {{info.school_name}}. All rights reserved.                       
               </div>
               
           </div>
       </div>
   </div>
</footer>
<!-- footer-end -->

school_project/templates/pages/gallery.html
{% extends "base.html" %}
{% load static %}
{% block content %}
            <!-- breadcrumb-area -->
             <section class="breadcrumb-area d-flex align-items-center" style="background-image: url('{% static 'img/testimonial/test-bg.png' %}')">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-12 col-lg-12">
                            <div class="breadcrumb-wrap text-left">
                                <div class="breadcrumb-title">
                                    <h2 style="color:#04AF70;">Gallery</h2>    
                                    <div class="breadcrumb-wrap">
                              
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page" >Gallery</li>
                                    </ol>
                                </nav>
                            </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </section>
            <!-- breadcrumb-area-end -->
			<!-- gallery-area -->
            <section id="work" class="pt-120 pb-90">
                <div class="container">                  
					<div class="portfolio ">
                        <div class="row align-items-center mb-50 text-center">                          
                            <div class="col-lg-12">
                                 <div class="my-masonry">
                            <div class="button-group filter-button-group ">
                                <a href="{% url 'basic:gallery_page'  %}"><button class="active"> All Gallery</button></a>
                               {% if gallery_categories %}
                               {% for category in gallery_categories%}
								 <a href="{% url 'basic:category_gallery' category.id %}"> <button > {{category}} </button></a>
                                 {% endfor %}

                                {% else %}
                                    <p> No gallery image found !! </p>
                                {% endif %}
							</div>
                        </div>
                            </div>
                        </div>
                      

                <div class="grid col3">

                    {% for gallery in galleries %}
				   	<div class="grid-item seo">                        	
                            <div class="case-study-box">
                              <div class="case-study-img">
                                   <img src="{{gallery.image.url}}" alt="protfolio">
                                </div>
                               <div class="case-study-content">
                                    
                                    <h5><a href="{% url 'basic:gallery_detail' gallery.id %}">{{gallery.title}}</a></h5> 
                                </div>
                            </div>
                    </div>
                    {% endfor %}
                                     
                    </div>

        </div>
                </div>
            </section>
             <!-- gallery-area-end -->
            
           
        </main>
        <!-- main-area-end -->
       
            {% endblock %}

school_project/templates/pages/gallery_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
            <!-- breadcrumb-area -->
            <section class="breadcrumb-area d-flex align-items-center" style="background-image: url('{% static 'img/testimonial/test-bg.png' %}')">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-12 col-lg-12">
                            <div class="breadcrumb-wrap text-left">
                                <div class="breadcrumb-title">
                                    <h2 style="color:#04AF70;">Gallery Details</h2>    
                                    <div class="breadcrumb-wrap">
                              
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb">
                                        <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Gallery Detail</li>
                                    </ol>
                                </nav>
                            </div>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </section>
            <!-- breadcrumb-area-end -->
			<!-- Project Detail -->
    <section class="project-detail">
        <div class="container">
            <!-- Upper Box -->
            <div class="upper-box">
                <div class="single-item-carousel owl-carousel owl-theme">
                    <figure class="image"><img src="{{one_gallery.image.url}}" alt=""></figure>    
                </div>
            </div>

            <!-- Lower Content -->
            <div class="lower-content">
                <div class="row">
                    <div class="text-column col-lg-12 col-md-12 col-sm-12">
                        <div class="inner-column">
                            <h4>{{one_gallery.title}}</h4>
                            <p>{{one_gallery.description}}</p>
                      
                        </div>
                    </div>

                    
                </div>
                
                
            </div>


        </div>
    </section>
    <!--End Project Detail -->

			
         
        </main>
        <!-- main-area-end -->
    {%endblock%}

school_project/templates/pages/nav.html
{% load static %}
<!-- header -->
<header class="header-area header-three">  
    <div id="header-sticky" class="menu-area">
        <div class="container">
            <div class="second-menu">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-2">
                        <div class="logo">
                            <a href="index.html"><img src="{{info.school_logo.url}}" alt="logo"></a>
                        </div>
                    </div>
                    <div class="col-xl-8 col-lg-8">
                      
                        <div class="main-menu text-right text-xl-right">
                            <nav id="mobile-menu" style="display: block;">
                                <ul>
                                    <li class="sub">
                                        <a style="color:#04AF70;" href="{% url 'basic:home_page' %}">Home</a>
                                    </li>
                                    <li><a style="color:#04AF70;" href="{% url 'basic:about_page' %}">About Us</a></li>

                                    <li><a style="color:#04AF70;" href="{% url 'basic:subject_page' %}">Subject We Teach</a></li>
                                 
                                    <li><a style="color:#04AF70;" href="{% url 'basic:event_page' %}">Events</a></li>
                                    <li><a style="color:#04AF70;" href="{% url 'basic:gallery_page' %}">Gallery</a></li>
                                    
                                    <li><a style="color:#04AF70;" href="{% url 'basic:news_page' %}">News</a></li>                   
                                  
                                    <li><a style="color:#04AF70;" href="{% url 'basic:contact_page' %}">Contact</a></li>                                               
                                </ul>
                            </nav>
                        </div>
                    </div>   
                    <div class="col-xl-2 col-lg-2 text-right d-none d-xl-block mt-30 mb-30">
                        <div class="search-top2">
                           <ul>
                               
                                <li><a href="#" class="menu-tigger"><i class="fas fa-search"></i></a></li>
                                <li><a href="#" class="menu-tigger"><img src="{% static 'img/icon/menu.png' %}" alt="logo"></a></li>
                            </ul>
                        </div>
                    </div>
                  
                    
                        <div class="col-12">
                            <div class="mobile-menu"></div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- header-end -->
<!-- offcanvas-area -->
        <div class="offcanvas-menu">
        <span class="menu-close"><i class="fas fa-times"></i></span>
      <form role="search" method="get" id="searchform"   class="searchform" action="http://wordpress.zcube.in/xconsulta/">
                        <input type="text" name="s" id="search" value="" placeholder="Search"  />
                        <button><i class="fa fa-search"></i></button>
                    </form>

            
            <div id="cssmenu3" class="menu-one-page-menu-container">
                <ul id="menu-one-page-menu-2" class="menu">
                    <li class="menu-item menu-item-type-custom menu-item-object-custom"><a style="color:#04AF70;" href="{% url 'basic:home_page' %}">Home</a></li>
                    <li class="menu-item menu-item-type-custom menu-item-object-custom"><a href="{% url 'basic:about_page' %}">About Us</a></li>
                    <li class="menu-item menu-item-type-custom menu-item-object-custom"><a href="{% url 'basic:subject_page' %}">Subject We Teach</a></li>
                     <li class="menu-item menu-item-type-custom menu-item-object-custom"><a href="{% url 'basic:event_page' %}">Events </a></li>
                     <li class="menu-item menu-item-type-custom menu-item-object-custom"><a href="{% url 'basic:gallery_page' %}">Gallery</a></li>
                     <li class="menu-item menu-item-type-custom menu-item-object-custom"><a href="{% url 'basic:news_page' %}">News </a></li>
                    <li class="menu-item menu-item-type-custom menu-item-object-custom"><a href="{% url 'basic:contact_page' %}">Contact</a></li>
                </ul>
            </div>  
            
            <div id="cssmenu2" class="menu-one-page-menu-container">
                <ul id="menu-one-page-menu-1" class="menu">
                    <li class="menu-item menu-item-type-custom menu-item-object-custom"><a href="#home"><span>{{info.phone_number.phone_number}}</span></a></li>
                    <li class="menu-item menu-item-type-custom menu-item-object-custom"><a href="#howitwork"><span>{{info.email}}</span></a></li>
                </ul>
            </div>                
    </div>
    <div class="offcanvas-overly"></div>
         <!-- offcanvas-end -->